version: '3.0'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file:
      - .development.env
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:12
    container_name: db
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  node_modules: